"""Primera migracion

Revision ID: 30173e2f710f
Revises: 
Create Date: 2023-02-22 21:15:39.083382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30173e2f710f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caso', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
