"""empty message

Revision ID: 6343be291d3d
Revises: a967a0429d98
Create Date: 2023-03-08 17:01:53.430542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6343be291d3d'
down_revision = 'a967a0429d98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cita_medica')
    with op.batch_alter_table('caso', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cita_medica')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cita_medica', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'cita_medica', ['cita_medica'], ['id'])

    op.create_table('cita_medica',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fecha', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('medico_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'Pendiente por asignar'"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
