"""Estado caso default: pendiente

Revision ID: bd1e087c687b
Revises: 30173e2f710f
Create Date: 2023-02-22 21:23:50.231550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd1e087c687b'
down_revision = '30173e2f710f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), server_default='Pendiente', nullable=True))
        batch_op.drop_column('estado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
