version: "3.8"

services:
  pyapp-salud:
    env_file: variables-prod-salud.env
    container_name: pyapp-salud
    build: .
    command: bash -c "gunicorn -w 1 --bind 0.0.0.0:8001 flaskr.app:app"
    volumes:
      - .:/app
    ports:
      - 8001:8001
    restart: always
    depends_on:
      - redis
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - pyapp-salud
  celery_worker:
    container_name: celery_worker
    restart: always
    build: .
    volumes:
      - .:/app
    command: celery -A flaskr.services.celery_app worker --loglevel=INFO
    environment:
      - REDIS_HOST=redis
    depends_on:
      - pyapp-salud
      - redis
  redis:
    container_name: redis
    image: redis:6.2-alpine