version: "3.8"

services:
  pyapp-salud:
    env_file: variables-prod-salud.env
    container_name: pyapp-salud
    build: .
    command: bash -c "gunicorn -w 1 --bind 0.0.0.0:8001 flaskr.app:app"
    volumes:
      - .:/app
    ports:
      - 8001:8001
    restart: always
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - pyapp-autenticacion