version: '3.8'

services:
  angular:
    container_name: angular
    build: ./dermoapp
    volumes:
      - './dermoapp:/usr/src/app'
    ports:
      - '4200:4200'
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"