name: ci-gestiondermatologia

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          cd gestion_dermatologia
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          cd gestion_dermatologia
          export DB_URI="sqlite:////tmp/test_salud.db" 
          export AUTH_BASE_URI=http://0.0.0.0
          pytest --cov-report term --cov=flaskr tests/